# Generated by Django 4.1.2 on 2022-10-30 14:18

import account.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('avatar', models.ImageField(blank=True, default='static/no_avatart.png', upload_to=account.utils.get_avatar_path, verbose_name='avatar')),
                ('bio', models.CharField(blank=True, max_length=150, verbose_name='bio')),
                ('date_of_birth', models.DateTimeField(blank=True, verbose_name='date of birth')),
                ('website', models.URLField(blank=True, verbose_name='website')),
            ],
        ),
    ]
