# Generated by Django 4.1.2 on 2022-11-02 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_onlinestatus_block'),
        ('account', '0002_alter_profile_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(related_name='+', through='activity.Block', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(related_name='followers', through='activity.Follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
