# Generated by Django 4.1.2 on 2022-10-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateTimeField(null=True, verbose_name='date of birth'),
        ),
    ]
