# Generated by Django 4.1.2 on 2022-11-02 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_onlinestatus_options_alter_onlinestatus_table'),
        ('notification', '0001_initial'),
        ('account', '0003_user_blocked_users_user_followings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blocked_users',
        ),
        migrations.AddField(
            model_name='user',
            name='bell_enablings',
            field=models.ManyToManyField(related_name='bell_enablers', through='notification.Bell', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='blockings',
            field=models.ManyToManyField(related_name='blockers', through='activity.Block', to=settings.AUTH_USER_MODEL),
        ),
    ]
