# Generated by Django 4.1.2 on 2022-10-30 14:32

import account.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='no_avatart.png', upload_to=account.utils.get_avatar_path, verbose_name='avatar'),
        ),
    ]
