# Generated by Django 4.1.2 on 2022-11-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.IntegerField(choices=[(0, 'truth_social'), (1, 'follow'), (2, 'like'), (3, 'mention'), (4, 'retweet'), (5, 'new_tweet')], verbose_name='notification type'),
        ),
    ]
