# Generated by Django 4.1.2 on 2022-11-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_notif_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bell',
            options={'verbose_name': 'bell', 'verbose_name_plural': 'bells'},
        ),
    ]
