# Generated by Django 4.1.2 on 2022-11-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_onlinestatus_block'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlinestatus',
            options={'verbose_name': 'online status', 'verbose_name_plural': 'online status'},
        ),
        migrations.AlterModelTable(
            name='onlinestatus',
            table='OnlineStatus',
        ),
    ]
