# Generated by Django 4.1.2 on 2022-11-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_onlinestatus_options_alter_onlinestatus_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinestatus',
            name='last_seen',
        ),
    ]
